# Step 3) Multi-Model Eval: OpenAI family

In [ ]:
import os  ### Initializing variables
while not os.path.isdir("src"):
    os.chdir("..")
print("Working directory set to repo root:", os.getcwd())

Working directory set to repo root: d:\TherapyLM-Design-Project

In [ ]:
import sys  
sys.path.append("src")

from multi_llm_eval import run_multi_model_eval, report_multi_model_metrics, PROVIDERS

MY_MODELS = ['gpt-5.6-sol', 'gpt-5.6-terra']
for m in MY_MODELS:
    print(m, "->", PROVIDERS[m]["family"])

gpt-5.6-sol -> OpenAI
gpt-5.6-terra -> OpenAI

d:\TherapyLM-Design-Project\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
smoke = run_multi_model_eval(     ##smoke test
    input_path="data/processed/test.csv",
    models=MY_MODELS,
    n=5,
    max_workers=5,
)
report_multi_model_metrics(smoke)

Sampled 4 posts (the SAME set will be used for every model).
status
Normal        2
Depression    1
Suicidal      1
Name: count, dtype: int64


============================================================
gpt-5.6-sol  (OpenAI)
============================================================

gpt-5.6-sol: 100%|██████████| 4/4 [00:08<00:00,  2.10s/it]

  Saved 4 rows to results/tables/multi_llm_gpt-5_6-sol.csv

============================================================
gpt-5.6-terra  (OpenAI)
============================================================

gpt-5.6-terra: 100%|██████████| 4/4 [00:02<00:00,  1.86it/s]

  Saved 4 rows to results/tables/multi_llm_gpt-5_6-terra.csv

Saved combined results (8 rows total) to results/tables/multi_llm_all_results.csv
        model family  n  accuracy  macro_f1  weighted_f1
gpt-5.6-terra OpenAI  4      0.75  0.380952     0.833333
  gpt-5.6-sol OpenAI  4      0.50  0.238095     0.583333

           model  family  n  accuracy  macro_f1  weighted_f1
0  gpt-5.6-terra  OpenAI  4      0.75  0.380952     0.833333
1    gpt-5.6-sol  OpenAI  4      0.50  0.238095     0.583333

### Full 500 posts run

In [4]:
full = run_multi_model_eval(
    input_path="data/processed/test.csv",
    models=MY_MODELS,
    n=500,
    max_workers=10,
)
report_multi_model_metrics(full)

Sampled 500 posts (the SAME set will be used for every model).
status
Normal                  155
Depression              148
Suicidal                104
Anxiety                  36
Bipolar                  25
Stress                   23
Personality disorder      9
Name: count, dtype: int64


============================================================
gpt-5.6-sol  (OpenAI)
============================================================

gpt-5.6-sol: 100%|██████████| 500/500 [01:54<00:00,  4.35it/s]

  Saved 500 rows to results/tables/multi_llm_gpt-5_6-sol.csv

============================================================
gpt-5.6-terra  (OpenAI)
============================================================

gpt-5.6-terra: 100%|██████████| 500/500 [01:26<00:00,  5.77it/s]

  Saved 500 rows to results/tables/multi_llm_gpt-5_6-terra.csv

Saved combined results (1000 rows total) to results/tables/multi_llm_all_results.csv
        model family   n  accuracy  macro_f1  weighted_f1
  gpt-5.6-sol OpenAI 500     0.638  0.583368     0.629759
gpt-5.6-terra OpenAI 500     0.656  0.572865     0.648028

           model  family    n  accuracy  macro_f1  weighted_f1
0    gpt-5.6-sol  OpenAI  500     0.638  0.583368     0.629759
1  gpt-5.6-terra  OpenAI  500     0.656  0.572865     0.648028