# Multi-Model Eval: Gemini family

Runs the gemini-3.1-pro, gemini-3.6-flash model on the same stratified 500-post
sample every other family-notebook uses

In [1]:
import os
while not os.path.isdir("src"):
    os.chdir("..")
print("Working directory set to repo root:", os.getcwd())

Working directory set to repo root: d:\TherapyLM-Design-Project

In [2]:
import sys
sys.path.append("src")

from multi_llm_eval import run_multi_model_eval, report_multi_model_metrics, PROVIDERS

MY_MODELS = ['gemini-3.1-pro-preview', 'gemini-3.6-flash']
for m in MY_MODELS:
    print(m, "->", PROVIDERS[m]["family"])

gemini-3.1-pro-preview -> Google
gemini-3.6-flash -> Google

d:\TherapyLM-Design-Project\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Smoke test (5 posts per model)

In [3]:
smoke = run_multi_model_eval(
    input_path="data/processed/test.csv",
    models=MY_MODELS,
    n=5,
    max_workers=3,
)
report_multi_model_metrics(smoke)

Sampled 4 posts (the SAME set will be used for every model).
status
Normal        2
Depression    1
Suicidal      1
Name: count, dtype: int64


============================================================
gemini-3.1-pro-preview  (Google)
============================================================

gemini-3.1-pro-preview: 100%|██████████| 4/4 [00:18<00:00,  4.59s/it]

  Saved 4 rows to results/tables/multi_llm_gemini-3_1-pro-preview.csv

============================================================
gemini-3.6-flash  (Google)
============================================================

gemini-3.6-flash: 100%|██████████| 4/4 [00:04<00:00,  1.11s/it]

  Saved 4 rows to results/tables/multi_llm_gemini-3_6-flash.csv

Saved combined results (8 rows total) to results/tables/multi_llm_all_results.csv
                 model family  n  accuracy  macro_f1  weighted_f1
gemini-3.1-pro-preview Google  4       0.5  0.238095     0.583333
      gemini-3.6-flash Google  4       0.5  0.238095     0.583333

                    model  family  n  accuracy  macro_f1  weighted_f1
0  gemini-3.1-pro-preview  Google  4       0.5  0.238095     0.583333
1        gemini-3.6-flash  Google  4       0.5  0.238095     0.583333

## Full run (500 posts per model)

In [4]:
full = run_multi_model_eval(
    input_path="data/processed/test.csv",
    models=MY_MODELS,
    n=500,
    max_workers=3,
)
report_multi_model_metrics(full)

Sampled 500 posts (the SAME set will be used for every model).
status
Normal                  155
Depression              148
Suicidal                104
Anxiety                  36
Bipolar                  25
Stress                   23
Personality disorder      9
Name: count, dtype: int64


============================================================
gemini-3.1-pro-preview  (Google)
============================================================

gemini-3.1-pro-preview:   3%|▎         | 16/500 [00:41<20:04,  2.49s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:   7%|▋         | 34/500 [01:19<15:11,  1.96s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  20%|██        | 100/500 [03:38<11:43,  1.76s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  27%|██▋       | 133/500 [04:41<08:31,  1.39s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  29%|██▉       | 146/500 [05:16<13:20,  2.26s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  30%|███       | 151/500 [05:28<11:17,  1.94s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  36%|███▌      | 178/500 [06:30<11:16,  2.10s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  37%|███▋      | 183/500 [06:44<12:08,  2.30s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  39%|███▉      | 194/500 [07:07<09:11,  1.80s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  41%|████      | 204/500 [07:34<10:30,  2.13s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  45%|████▌     | 225/500 [08:28<14:23,  3.14s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  51%|█████     | 256/500 [09:36<06:03,  1.49s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  53%|█████▎    | 266/500 [10:10<12:30,  3.21s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: HTTPSConnectionPool(host='aiplatform.googleapis.com', port=443): Read timed out. (read timeout=30) (waiting 1s)
gemini-3.1-pro-preview:  57%|█████▋    | 283/500 [10:57<13:52,  3.84s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  57%|█████▋    | 287/500 [11:10<10:39,  3.00s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: HTTPSConnectionPool(host='aiplatform.googleapis.com', port=443): Read timed out. (read timeout=30) (waiting 1s)
gemini-3.1-pro-preview:  58%|█████▊    | 292/500 [11:23<08:31,  2.46s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  62%|██████▏   | 312/500 [12:07<05:27,  1.74s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  64%|██████▎   | 318/500 [12:24<08:59,  2.97s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  73%|███████▎  | 363/500 [14:05<03:50,  1.68s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  76%|███████▌  | 381/500 [14:44<03:52,  1.95s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  84%|████████▎ | 418/500 [16:02<01:58,  1.44s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  85%|████████▍ | 423/500 [16:19<02:57,  2.31s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview:  96%|█████████▌| 480/500 [18:28<00:37,  1.85s/it]    [gemini-3.1-pro-preview] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.1-pro-preview:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.1-pro-preview: 100%|██████████| 500/500 [19:23<00:00,  2.33s/it]

  Saved 500 rows to results/tables/multi_llm_gemini-3_1-pro-preview.csv

============================================================
gemini-3.6-flash  (Google)
============================================================

gemini-3.6-flash:  51%|█████     | 256/500 [04:52<04:34,  1.12s/it]    [gemini-3.6-flash] retry 1/4 after error: 429 Client Error: Too Many Requests for url: https://aiplatform.googleapis.com/v1/publishers/google/models/gemini-3.6-flash:generateContent?key=AQ.Ab8RN6Imu6b3yTui1yLNmIx6yC5z-wGq78NZEM6DPY1Vmx25SQ (waiting 1s)
gemini-3.6-flash: 100%|██████████| 500/500 [09:29<00:00,  1.14s/it]

  Saved 500 rows to results/tables/multi_llm_gemini-3_6-flash.csv

Saved combined results (1000 rows total) to results/tables/multi_llm_all_results.csv
                 model family   n  accuracy  macro_f1  weighted_f1
gemini-3.1-pro-preview Google 500     0.682  0.604055     0.675719
      gemini-3.6-flash Google 500     0.670  0.595551     0.661354

                    model  family    n  accuracy  macro_f1  weighted_f1
0  gemini-3.1-pro-preview  Google  500     0.682  0.604055     0.675719
1        gemini-3.6-flash  Google  500     0.670  0.595551     0.661354