# Step 3c — Multi-Model Eval: Local (LM Studio) family


2 local models (`meta-llama-3.1-8b-instruct` and `google/gemma-4b-e4b`) on the SAME
stratified 500-post sample for testing.

In [1]:
import os
while not os.path.isdir("src"):
    os.chdir("..")
print("Working directory set to repo root:", os.getcwd())

Working directory set to repo root: /Users/sadmanshaharier/Documents/CODING - Mac/git repo projects/IUT-CSE/Design Project/TherapyLM-Design-Project

In [3]:
import sys
sys.path.append("src")

from multi_llm_eval import run_multi_model_eval, report_multi_model_metrics, PROVIDERS

LOCAL_MODELS = ["meta-llama-3.1-8b-instruct", "google/gemma-4b-e4b"]
for m in LOCAL_MODELS:
    print(m, "->", PROVIDERS[m]["family"])

meta-llama-3.1-8b-instruct -> Local (LM Studio)
google/gemma-4b-e4b -> Local (LM Studio)

## Part 1 — Llama 3.1 8B

In [4]:
smoke_llama = run_multi_model_eval(
    input_path="data/processed/test.csv",
    models=["meta-llama-3.1-8b-instruct"],
    n=5,
    max_workers=4,
)
report_multi_model_metrics(smoke_llama)

Sampled 4 posts (the SAME set will be used for every model).
status
Normal        2
Depression    1
Suicidal      1
Name: count, dtype: int64


============================================================
meta-llama-3.1-8b-instruct  (Local (LM Studio))
============================================================

meta-llama-3.1-8b-instruct: 100%|██████████| 4/4 [00:05<00:00,  1.36s/it]

  Saved 4 rows to results/tables/multi_llm_meta-llama-3_1-8b-instruct.csv

Saved combined results (4 rows total) to results/tables/multi_llm_all_results.csv
                     model            family  n  accuracy  macro_f1  weighted_f1
meta-llama-3.1-8b-instruct Local (LM Studio)  4       0.5  0.238095     0.583333

,model,family,n,accuracy,macro_f1,weighted_f1
0,meta-llama-3.1-8b-instruct,Local (LM Studio),4,0.5,0.238095,0.583333

In [5]:
full_llama = run_multi_model_eval(
    input_path="data/processed/test.csv",
    models=["meta-llama-3.1-8b-instruct"],
    n=500,
    max_workers=4,
)
report_multi_model_metrics(full_llama)

Sampled 500 posts (the SAME set will be used for every model).
status
Normal                  155
Depression              148
Suicidal                104
Anxiety                  36
Bipolar                  25
Stress                   23
Personality disorder      9
Name: count, dtype: int64


============================================================
meta-llama-3.1-8b-instruct  (Local (LM Studio))
============================================================

meta-llama-3.1-8b-instruct: 100%|██████████| 500/500 [12:02<00:00,  1.45s/it]

  Saved 500 rows to results/tables/multi_llm_meta-llama-3_1-8b-instruct.csv

Saved combined results (500 rows total) to results/tables/multi_llm_all_results.csv
                     model            family   n  accuracy  macro_f1  weighted_f1
meta-llama-3.1-8b-instruct Local (LM Studio) 500      0.55  0.442907     0.570884

,model,family,n,accuracy,macro_f1,weighted_f1
0,meta-llama-3.1-8b-instruct,Local (LM Studio),500,0.55,0.442907,0.570884

## Part 2 — Gemma 4B (e4b total  7.5b)

In [4]:
smoke_gemma = run_multi_model_eval(
    input_path="data/processed/test.csv",
    models=["google/gemma-4b-e4b"],
    n=5,
    max_workers=4,
)
report_multi_model_metrics(smoke_gemma)

Sampled 4 posts (the SAME set will be used for every model).
status
Normal        2
Depression    1
Suicidal      1
Name: count, dtype: int64


============================================================
google/gemma-4b-e4b  (Local (LM Studio))
============================================================

google/gemma-4b-e4b: 100%|██████████| 4/4 [00:34<00:00,  8.72s/it]

  Saved 4 rows to results/tables/multi_llm_google_gemma-4b-e4b.csv

Saved combined results (4 rows total) to results/tables/multi_llm_all_results.csv
              model            family  n  accuracy  macro_f1  weighted_f1
google/gemma-4b-e4b Local (LM Studio)  4       0.5  0.238095     0.583333

                 model             family  n  accuracy  macro_f1  weighted_f1
0  google/gemma-4b-e4b  Local (LM Studio)  4       0.5  0.238095     0.583333

In [5]:
full_gemma = run_multi_model_eval(
    input_path="data/processed/test.csv",
    models=["google/gemma-4b-e4b"],
    n=500,
    max_workers=4,
)
report_multi_model_metrics(full_gemma)

Sampled 500 posts (the SAME set will be used for every model).
status
Normal                  155
Depression              148
Suicidal                104
Anxiety                  36
Bipolar                  25
Stress                   23
Personality disorder      9
Name: count, dtype: int64


============================================================
google/gemma-4b-e4b  (Local (LM Studio))
============================================================

google/gemma-4b-e4b:  28%|██▊       | 141/500 [03:45<19:40,  3.29s/it]    [google/gemma-4b-e4b] retry 1/4 after error: label 'Pain' isn't one of the 7 categories (waiting 1s)
    [google/gemma-4b-e4b] retry 2/4 after error: label 'Pain' isn't one of the 7 categories (waiting 2s)
    [google/gemma-4b-e4b] retry 3/4 after error: label 'Pain' isn't one of the 7 categories (waiting 4s)
google/gemma-4b-e4b:  29%|██▊       | 143/500 [03:59<28:47,  4.84s/it]    [google/gemma-4b-e4b] retry 4/4 after error: label 'Pain' isn't one of the 7 categories (waiting 8s)
google/gemma-4b-e4b:  72%|███████▏  | 361/500 [11:49<04:29,  1.94s/it]    [google/gemma-4b-e4b] retry 1/4 after error: label 'Fatigue' isn't one of the 7 categories (waiting 1s)
google/gemma-4b-e4b: 100%|██████████| 500/500 [16:18<00:00,  1.96s/it]

  Saved 500 rows to results/tables/multi_llm_google_gemma-4b-e4b.csv

Saved combined results (500 rows total) to results/tables/multi_llm_all_results.csv
              model            family   n  accuracy  macro_f1  weighted_f1
google/gemma-4b-e4b Local (LM Studio) 499  0.607214  0.510243     0.607412

,model,family,n,accuracy,macro_f1,weighted_f1
0,google/gemma-4b-e4b,Local (LM Studio),499,0.607214,0.510243,0.607412